### ISSUE TITLE
漫画标题带有等英文字符，无法生成文件夹下载

### ISSUE THREAD

**Issue by 595600533** [MOMOYATW/bilibili_manga_downloader#1]
因Windows限制无法生成带有\ / ： * ？" < > |字符的文件夹，但b漫上有些漫画的标题用了此类英文字符，所以造成无法生成文件夹，从而造成无法下载。举例如《在地下城寻求邂逅是否搞错了什么》第15话“第015话—购物惹麻烦??”

**Comment by MOMOYATW** [comment]
感谢指出~
