### ISSUE TITLE
对于番外等章节文件夹命名的问题

### ISSUE THREAD

**Issue by huanqianhan** [MOMOYATW/bilibili_manga_downloader#10]
![屏幕截图 2023-01-14 101718](https://user-images.githubusercontent.com/76838560/212446372-a5348f22-aeac-4693-9dfb-10a422163b8b.png)
番外章节的序号直接给了一个特别大数字，而且没有标记这是番外篇，不清楚这样命名是设计如此还是bug。如果是Bug个人感觉可以这样做如果前面一话是35话，后面是番外。可以这样命名  35话 ，35.1话 番外篇 ，35.2话番外篇.............同时对于文件的1排序可以前面以0填充吗      如001.。。。。。。。。100,101,102这样排序

**Comment by huanqianhan** [comment]
同时安装新版本的话设置里面的token和文件夹路径这些以及下载记录都会清空

**Comment by MOMOYATW** [comment]
这确实是个bug，这应该是45.5，中间的小数点在规范文件名的时候被抹掉了，下个版本修复。

**Comment by MOMOYATW** [comment]
之所以记录清空是由于安装程序将原安装目录覆盖所致，而记录文件在安装目录下。下个版本将会将记录文件存放在用户目录下，但更新下个版本无法避免会再次覆盖本次的设置。

**Comment by MOMOYATW** [comment]
关于文件排序填充0，我用comic screen测试了下，不填充0可以正常识别。填充零后再结合小数点，非常别扭，所以还是维持原状。如果有程序无法正确识别请再comment。

**Comment by MOMOYATW** [comment]
在修复issue #19 时，所做的改动导致这个issue再次出现，将在下一版本修复。
