### ISSUE TITLE
境外的漫画无法下载

### ISSUE THREAD

**Issue by huanqianhan** [MOMOYATW/bilibili_manga_downloader#13]
哔哩哔哩境外版漫画好像无法下载，挂了代理网页端可以观看，下载器可以解析，但是无法添加到下载队列

**Comment by MOMOYATW** [comment]
境外版可以下载，将代理设置为全局模式即可。

![image](https://user-images.githubusercontent.com/43531252/212469314-57c3ec53-5310-4d0f-a37b-7930c70faefd.png)
