### ISSUE TITLE
下载文件名排序问题

### ISSUE THREAD

**Issue by huanqianhan** [MOMOYATW/bilibili_manga_downloader#14]
明明下载的是第一话为什么序号是2呢
![image](https://user-images.githubusercontent.com/76838560/212478268-cf928fed-3f79-4bd3-b80e-82ba763550ea.png)

**Comment by huanqianhan** [comment]
> 明明下载的是第一话为什么序号是2呢 ![image](https://user-images.githubusercontent.com/76838560/212478268-cf928fed-3f79-4bd3-b80e-82ba763550ea.png)
https://manga.bilibili.com/detail/mc26985漫画链接

**Comment by MOMOYATW** [comment]
![image](https://user-images.githubusercontent.com/43531252/212482448-c5c3bfe9-fda6-4e21-a6a5-c0a09234a45f.png)

排序使用的序号来自b站后台响应的ord字段，这个漫画确实ord是从2开始的。这种个别漫画出现的问题也不太好调整，如果想办法处理的话，命名时用`{short_title}` 可能在这里比较合适。但短标题也不总是按顺序排的，理论上ord应该是最接近需求的。

**Comment by MOMOYATW** [comment]
目前看来是小概率问题，暂时不做改进。
