### ISSUE TITLE
[BUG]3.0.2版本设置名称格式中不支持英文中括号

### ISSUE THREAD

**Issue by ErrorPower2001** [MOMOYATW/bilibili_manga_downloader#15]
3.0.2版本中，设置的名称格式中包含的中括号下载后一律消失

漫画文件夹名称格式  
[{authors}][{id}][{title}][bilibili]

下载后的文件夹名称上没有了中括号

**Comment by MOMOYATW** [comment]
由于之前经常出现文件名带有非法字符导致无法正常下载的情况，因此现在采取了对文件名更加严格的筛查策略。下个版本会进一步放宽。
