### ISSUE TITLE
[V3.0.2]增加漫画详情页「回到顶部」按钮或排序功能

### ISSUE THREAD

**Issue by ErrorPower2001** [MOMOYATW/bilibili_manga_downloader#16]
平时下载连载漫画会只需要下载最后一话，此时需要拖动进度条至底部点击后，再拖动进度条到顶部点击下载，可以增加「回到顶部」功能按钮或排序功能较少繁琐操作。

不过因为基于Electron，可以通过键盘的Home与End键快速移动，本issue可驳回。

**Comment by MOMOYATW** [comment]
下个版本考虑调整漫画显示顺序，并加入返回顶部按钮。

**Comment by MOMOYATW** [comment]
已更新
