### ISSUE TITLE
六点建议（四点已完成）

### ISSUE THREAD

**Issue by lb-fes** [MOMOYATW/bilibili_manga_downloader#17]
1. 软件安装能不装到 C 盘或者有个便携版。
2. 点击登录获取 token ：登录后关闭窗口不会马上显示获取到的 Token ，点了 “保存设置” 之后才会显示，我还以为没获取到呢。（目前在下载器登录后，网页端没有退出登录）
3. 每次通过关键字搜索漫画，都会先被 “没有搜索结果哟” 晃一下，才会显示搜索结果
4. 漫画详情页 UI 过大，在漫画话数多的情况下，效率不高，可以适当调小。 
5. 我主要是用来下载 **特典** 的，特典能与正文分开保存在漫画目录下的不同文件夹里就好了。
6. 点 “×” 关闭窗口可以选择退出应用还是最小化到托盘。

最后，祝开发者，兔年快乐！万事如意！

**Comment by MOMOYATW** [comment]
春节同乐！
1. 可以在release中加入免安装版，但是自动升级程序可能会在新版本出现时自动将程序安装到C盘，后续会考虑修改编译配置。
2. 下个版本将改进。
3. 下个版本将改进。
4. 本意是尽可能展示每集的信息，方便定位。后续考虑增加按钮修改页面布局。目前也在考虑增加shift多选功能。
5. 特典存放位置不同人可能会有不同偏好，后续考虑自定义保存位置，可能会在下个版本加入。
6. 下个版本将改进。

**Comment by MOMOYATW** [comment]
1，2，3，6 已完成。
