### ISSUE TITLE
愚蠢天使与恶魔共舞第41话Little little......下载文件不完整

### ISSUE THREAD

**Issue by e-onion** [MOMOYATW/bilibili_manga_downloader#19]
https://manga.bilibili.com/mc28085/517561?from=manga_detail
只有这一话下载进度不动，下载文件不完整
![屏幕截图 2023-02-02 204735](https://user-images.githubusercontent.com/47427873/216330941-892797e5-1a6a-4df6-9573-a6ac8b8721cb.png)
![屏幕截图 2023-02-02 204820](https://user-images.githubusercontent.com/47427873/216330992-0e38e6a7-2ac3-4772-b77e-da56ad8ed772.png)
![屏幕截图 2023-02-02 204837](https://user-images.githubusercontent.com/47427873/216331020-a8813431-829d-4494-84c2-d691ab914388.png)

**Comment by MOMOYATW** [comment]
感谢反馈，该bug仍然是文件夹命名所致，将在下一版本修复。

**Comment by MOMOYATW** [comment]
更新后请将该话所在文件夹删除后，再重新下载此话。程序检测到目录下存在同名文件时会自动跳过下载。
