### ISSUE TITLE
请问一下，未来作者有支持下载b漫限时特典的可能吗？

### ISSUE THREAD

**Issue by xuelandongman** [MOMOYATW/bilibili_manga_downloader#2]
![IMG_20220513_090639](https://user-images.githubusercontent.com/94791957/168191399-71de15cf-6ce5-490f-8446-de32ca452922.jpg)
![IMG_20220513_090712](https://user-images.githubusercontent.com/94791957/168191410-3a7ee8f4-8220-437b-bafe-602d73beb91e.jpg)
@MOMOYATW

**Comment by MOMOYATW** [comment]
了解了一下，目前特典仅支持手机端查看，现在手边没有抓包工具，暂时没法弄。

**Comment by xuelandongman** [comment]
嗯嗯  明白了 谢谢٩(*´◒`*)۶

**Comment by MOMOYATW** [comment]
最新版本已支持
