### ISSUE TITLE
漫画含有 视频预告 的时候，后续章节下载会被卡住

### ISSUE THREAD

**Issue by lb-fes** [MOMOYATW/bilibili_manga_downloader#20]
如果漫画含有**视频预告**，全选后下载，在**视频预告**下载完成后，该漫画的下载队列会被卡住。

#### URL：
https://manga.bilibili.com/detail/mc31506?from=manga_search
https://manga.bilibili.com/detail/mc31034?from=manga_search

**Comment by MOMOYATW** [comment]
最近比较忙，预计在未来两周内排查修复。

**Comment by MOMOYATW** [comment]
这是一个视频和图片任务一起下载时会触发的bug，将在下一版本修复，当前的workaround是将视频任务和图片任务分次添加到任务列表中。
