### ISSUE TITLE
关于境外班漫画下载的问题

### ISSUE THREAD

**Issue by huanqianhan** [MOMOYATW/bilibili_manga_downloader#22]
境外版漫画是对节点有什么要求吗，试了git另外一个开发者的B站下载漫话下载软件，我的节点都可以下载，但是作者你的就一直无法添加到任务队列，也找好几个朋友试了，都没反应，不太明白

**Comment by MOMOYATW** [comment]
我使用的是clash for windows的TUN模式，其他代理软件的全局代理模式也应该可以。总之，只要是系统级代理应该就可以让软件开始下载。
后续会研究一下这里是否可以改进。

**Comment by huanqianhan** [comment]
> 我使用的是 clash for windows的TUN模式，其他代理软件的全局代理模式也应该可以。总之，只要是系统级代理应该就可以让软件开始下载。 后续会研究一下这里是否可以改进。

多谢解答已经解决了
