### ISSUE TITLE
境外版下载问题

### ISSUE THREAD

**Issue by 123joel1** [MOMOYATW/bilibili_manga_downloader#23]
作者你好 境外版可以解析 但无法加入下载队列中 clash开了全局模式

**Comment by MOMOYATW** [comment]
请参考issue #22

**Comment by MOMOYATW** [comment]
如果使用clash，除了切换到全局模式，还需要启用TUN模式。

**Comment by 123joel1** [comment]
启用TUN模式依然无法加入下载队列

**Comment by MOMOYATW** [comment]
检查一下Clash的Logs，bilibili有关的流量是否走的代理节点。
如果迫切需要下载，我建议如下操作：
1. 将cfw和bilibili manga downloader都完全退出。
2. 启动cfw，按照cfw的官方教程开启TUN模式，关闭系统代理选项，并切换到全局模式。确保全局模式使用的节点为境外节点。
3. 打开bilibili manga downloader程序，尝试下载境外漫画。

下一版本，我将尝试对这个问题进行改善。

**Comment by 123joel1** [comment]
可能是我网络的问题依然无法加入下载队列 不论如何感谢你的回复 祝你生活愉快

**Comment by Gedminer** [comment]
同问题，确定走代理了，我使用了网卡模式
![image](https://user-images.githubusercontent.com/59013843/235938284-384b38aa-ab6c-4b07-a890-f22913bafeba.png)
------------------------------------------------
而且获取的章节也有问题，显示我解锁了。但是我实际根本没解锁这么多章。
![image](https://user-images.githubusercontent.com/59013843/235939663-37bb0b8d-b9ce-4489-ba10-fbe8962c216b.png)
![image](https://user-images.githubusercontent.com/59013843/235940366-867f8600-9dcb-4f8b-88f2-f27a51b17f01.png)

------------------------------------------------
而有的漫画解锁了，他又显示没解锁。
![image](https://user-images.githubusercontent.com/59013843/235940132-8f585bf1-7fd9-478b-8839-6c35b17847e7.png)
![image](https://user-images.githubusercontent.com/59013843/235940774-61260803-bcd0-4d26-accf-6e09be168caf.png)
------------------------------------------------
就十分令人迷惑

**Comment by MOMOYATW** [comment]
> ## 同问题，确定走代理了，我使用了网卡模式
> ![image](https://user-images.githubusercontent.com/59013843/235938284-384b38aa-ab6c-4b07-a890-f22913bafeba.png)
> 而且获取的章节也有问题，显示我解锁了。但是我实际根本没解锁这么多章。 ![image](https://user-images.githubusercontent.com/59013843/235939663-37bb0b8d-b9ce-4489-ba10-fbe8962c216b.png) ![image](https://user-images.githubusercontent.com/59013843/235940366-867f8600-9dcb-4f8b-88f2-f27a51b17f01.png)
> 
> ## 而有的漫画解锁了，他又显示没解锁。
> ![image](https://user-images.githubusercontent.com/59013843/235940132-8f585bf1-7fd9-478b-8839-6c35b17847e7.png)
> ![image](https://user-images.githubusercontent.com/59013843/235940774-61260803-bcd0-4d26-accf-6e09be168caf.png)
> 就十分令人迷惑

没购买的漫画解锁了是什么情况，可以细说吗？
