### ISSUE TITLE
请问购买后的漫画无法下载吗？

### ISSUE THREAD

**Issue by Discut** [MOMOYATW/bilibili_manga_downloader#24]
APP里已购买
![image](https://github.com/MOMOYATW/bilibili_manga_downloader/assets/71692038/5c6413eb-f0c0-4326-887b-fcd25cee2d2d)

软件里无法选中
![image](https://github.com/MOMOYATW/bilibili_manga_downloader/assets/71692038/ca2fbfeb-a50c-4f5c-8993-484701869bc8)

已配置token
![image](https://github.com/MOMOYATW/bilibili_manga_downloader/assets/71692038/2f5781b8-0979-469a-bea1-4fe035ec9e4c)

**Comment by Daniel011011** [comment]
一样，购买了的内容无法下载

**Comment by MOMOYATW** [comment]
在获取完token后，点击设置页面的“保存设置”可以解决这个问题。

**Comment by Discut** [comment]
已解决。我还以为会自动保存token🙀。

**Comment by Discut** [comment]
> 在获取完token后，点击设置页面的“保存设置”可以解决这个问题。

谢谢
