### ISSUE TITLE
在README中添加构建指南

### ISSUE THREAD

**Issue by chenxiex** [MOMOYATW/bilibili_manga_downloader#25]
release下似乎只有windows版的发布。希望在README中添加构建指南，这样方便其它系统的用户也可以自己编译使用。（我自己摸索了一下，至少linux下是可以正常编译运行的）

**Comment by MOMOYATW** [comment]
尚没有尝试过在linux下编译，也没有在linux下运行过，因此无法给出详细指南，如果想要自行编译可以尝试执行以下命令：
```
npm install
npm run build
```
供参考

**Comment by MOMOYATW** [comment]
详细构建方法现已添加至[README](https://github.com/MOMOYATW/bilibili_manga_downloader?tab=readme-ov-file#%E8%87%AA%E8%A1%8C%E7%BC%96%E8%AF%91%E4%B8%8E%E8%BF%90%E8%A1%8C)

**Comment by chenxiex** [comment]
谢谢提供Linux支持。我正在尝试将该软件打包并提交至AUR，现在有个问题是该软件采用什么license？

**Comment by MOMOYATW** [comment]
协议已更新，本项目采用MIT协议

**Comment by chenxiex** [comment]
已经将该项目上传至AUR。使用Arch Linux及其衍生版本的用户，可以访问[https://aur.archlinux.org/packages/bilibili_manga_downloader-bin](https://aur.archlinux.org/packages/bilibili_manga_downloader-bin)安装。
