### ISSUE TITLE
RPG不动产 总是卡22话

### ISSUE THREAD

**Issue by xuelandongman** [MOMOYATW/bilibili_manga_downloader#4]
https://manga.bilibili.com/detail/mc30415?from=manga_person
![1](https://user-images.githubusercontent.com/94791957/176577407-ad1eb420-13bb-4915-a0f8-3427be9d5b12.PNG)

**Comment by xuelandongman** [comment]
@MOMOYATW 确实是工具的问题

**Comment by MOMOYATW** [comment]
排查发现是由于文件夹名称不能有"."造成的，将在近期修复。

**Comment by xuelandongman** [comment]
> 排查发现是由于文件夹名称不能有"."造成的，将在近期修复。

辛苦啦~

**Comment by MOMOYATW** [comment]
新版本已解决
