### ISSUE TITLE
在下载的时候进入漫画点击全部暂停没有反应

### ISSUE THREAD

**Issue by huanqianhan** [MOMOYATW/bilibili_manga_downloader#6]
同时希望可以支持断点续传，下载了一半断掉了，重新打开不知道没有下载记录了，顺便想问一下漫画的画质是最高的那个吗B站APP里面画质有三个选项，下载的时候是最高的画质的那个吗

**Comment by MOMOYATW** [comment]
1. 当前release的版本尚不支持下载线程的控制。最近已用electron对项目重写，新项目中任务的暂停与续传将被支持。
2. 目前新项目中正在考虑简单的记录存储功能。
3. 目前release版本是默认下载最高画质的，以后也不考虑增加选择画质选项。

**Comment by MOMOYATW** [comment]
b站不支持断点续传功能，因此改为了取消下载~pre-release版本已经发布，欢迎使用。
