### ISSUE TITLE
希望增加下载完成后可以打包为zip的功能

### ISSUE THREAD

**Issue by huanqianhan** [MOMOYATW/bilibili_manga_downloader#7]
漫画的最好阅读方式必然是安卓端设备，pc的漫画阅读体验是比较糟糕的。3.0版本的使用体验较之前的版本感觉有了很大的提高。在安卓端有一系列本地漫画阅读软件完美的支持了zip的压缩包阅读。体验十分良好。如comic screen,和Tachiyomi，阅读压缩包体验很棒，同时在文件移动和存储的方面也有一定的好处。如果可以的话希望增加对漫画封面的下载，对于安卓端的本地漫画软件支持识别文件名为cover的图片作为本地书架中的漫画封面。

**Comment by MOMOYATW** [comment]
下载封面将默认下载到漫画文件夹下。
压缩将被加为可选项，下载漫画数量变多后，压缩漫画的速度会变慢，可能会影响下载的速度。

**Comment by MOMOYATW** [comment]
新发布的pre-release已加入功能
