### ISSUE TITLE
自定义漫画文件夹名称似乎有bug

### ISSUE THREAD

**Issue by huanqianhan** [MOMOYATW/bilibili_manga_downloader#8]

**Comment by huanqianhan** [comment]
![屏幕截图 2023-01-13 163743](https://user-images.githubusercontent.com/76838560/212275849-1cd91f14-a360-4afd-8611-4afa4218f7db.png)
在这么命名的话有概率出现2个文件夹，文件夹混乱的情况。

**Comment by huanqianhan** [comment]
![屏幕截图 2023-01-13 164449](https://user-images.githubusercontent.com/76838560/212276933-cbb36ce9-685e-4c64-9964-defb780d334e.png)
好像还碰到了奇怪的问题下载不动，删除本地文件下载不动的那一话，然后客户端点删除的时候一直弹出这个界面

**Comment by MOMOYATW** [comment]
自定义漫画名称的问题没有办法复现，我刚刚测试设置同时可下载4个，下载17话，没有遇到你这个问题。

**Comment by MOMOYATW** [comment]
下载出问题的具体漫画名称和话数可以提供下吗，我看看能不能复现。

**Comment by huanqianhan** [comment]
> 下载出问题的具体漫画名称和话数可以提供下吗，我看看能不能复现。

感觉不好描述，我录制了视频，复现了这一过程
链接：https://pan.baidu.com/s/1dGSwGHBOf62yvU1ZOMjakw?pwd=v2zp 
提取码：v2zp 
--来自百度网盘超级会员V6的分享

**Comment by MOMOYATW** [comment]
我明白你的意思了，这个bug其实是已知问题引起的，现已修复。
