### ISSUE TITLE
希望可以增加自动下载更新章节的功能

### ISSUE THREAD

**Issue by huanqianhan** [MOMOYATW/bilibili_manga_downloader#9]
连载的漫画有时候过段时间就会更新，但是追的漫画一多就挨个下载某个更新的章节就很麻烦，追15本漫画每周就得15次下载更新的漫画，过程过于繁琐，因此希望增加这个功能

**Comment by MOMOYATW** [comment]
这个可以通过订阅RSS实现，[RSSHub](https://github.com/DIYgod/RSSHub)提供了B站漫画订阅接口`/bilibili/manga/update/:comicid`。不过目前版本的程序不支持最小化托盘，所以这个功能需要暂时放一下。

**Comment by MOMOYATW** [comment]
自动下载最新更新的漫画可能还涉及到购买问题。但是购买涉及到真实的货币交易，有出现因为程序bug造成利益损失的可能，因此暂时不能考虑发布这样的功能。可能会考虑自动下载已解锁的漫画。

**Comment by huahuahuaxiayu** [comment]
已购买的漫画还是显示未解锁，请问有办法解决吗？

**Comment by MOMOYATW** [comment]
请检查token是否正确设置。具体方法已在[readme](https://github.com/MOMOYATW/bilibili_manga_downloader#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)中给出。
